server:
  port: 8040
  tomcat:
    basedir: logistics/tomcat
  compression:
    mime-types: application/javascript,text/javascript,text/css
    enabled: true
    min-response-size: 2048
spring:
#  http:
#    multipart:
#      enabled: false
  application:
    name: steam #项目名称
  data:
    mongodb:
      host: 192.168.3.8
#      host: 127.0.0.1
      port: 27017
      database: steam0704
scan:
  packages: cn.bytecloud.steam